# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql2
  database: bracketify
  host: 127.0.0.1
  encoding: utf8
  port: 3306
  username: root
  password:

test:
  adapter: mysql2
  database: bracketify_test
  host: 127.0.0.1
  encoding: utf8
  port: 3306
  username: root
  password:
